prompts = [
"Frigid Ice Shimmer",
"Robotic Reso Ping",
"Saturated Solar Flare",
"Gentle Gale Glide",
"Sonic Satin Sweep",
"Twilight Triangle Tremor",
"Nebulous Nightfall",
"Percussive Pluck Pulse",
"Celestial Chime Cascade",
"Desert Dust Drift",
"Cosmic Choir Cloud",
"Magnetic Moon Moan",
"Velvet Vortex Vibration",
"Pristine Polar Ping",
"Galactic Glide Groove",
"Radiant Rainbow Ripple",
"Serene Silk Sway",
"Jungle Jive Jolt",
"Zen Zone Zephyr",
"Luminous Lunar Latch",
"Tidal Tsunami Twist",
"Virtual Vinyl Vroom",
"Enigmatic Ember Emanation",
"Primal Pulse Purr",
"Euphoric Ether Elevate",
"Dynamic Dune Drizzle",
"Phantom Photon Phase",
"Crystalline Cave Chirp",
"Aurora Arc Atmosphere",
"Energetic Ember Eruption",
"Soft Snow Sizzle",
"Enchanted Echo Envelop",
"Synthetic Sunbeam Surge",
"Mystic Mirage Melt",
"Oceanic Organ Oscillation",
"Hypnotic Halo Hiss",
"Majestic Monsoon Mood",
"Starry Sky Strum",
"Deep Dive Drop",
"Iridescent Icy Illusion",
"Tranquil Tree Twinkle",
"Melodic Meteor Mumble",
"Sonic Sandstorm Shift",
"Ethereal Earth Echo",
"Rhythmic Rain Resound",
"Vibrant Volcano Verve",
"Pulsing Planet Patter",
"Whispering Wind Whirl",
"Magnetic Mist Murmur",
"Elusive Electric Ebb",
"Lyrical Lava Loom",
"Polished Prism Pulse",
"Gleaming Galaxy Glide",
"Ambient Arctic Air",
"Dynamic Dawn Drift",
"Serendipitous Starlight Sing",
"Timeless Tidal Tune",
"Melancholic Moon Muse",
"Warm Wave Waltz",
"Symphonic Sun Sway",
"Delicate Dew Drop",
"Radiant Reef Resonance",
"Enigmatic Ether Echo",
"Soothing Space Sigh",
"Harmonious Horizon Hum",
"Fading Fantasy Flutter",
"Ambient Aurora Awe",
"Celestial Celesta Chorus",
"Timeless Timber Tone",
"Ethereal Ember Embrace",
"Resounding Rainforest Riff",
"Solar Synth Sing",
"Glacial Glow Groan",
"Lustrous Lunar Lure",
"Rhythmic Radiance Roar",
"Deep Dream Drizzle",
"Shimmering Shadow Shift",
"Melodic Mystic Murmur",
"Ambient Atmosphere Aura",
"Cosmic Cascade Choir",
"Gentle Genesis Glide",
"Polar Pulse Patter",
"Ethereal Euphoria Echo",
"Serene Sonic Swoosh",
"Luminous Lagoon Lilt",
"Radiant Rhapsody Ripple",
"Vibrant Vesper Vibration",
"Whispering Willow Wave",
"Solar Synth Sweep",
"Dynamic Dawn Drop",
"Mystic Moon Melody",
"Nebula Night Nudge",
"Oceanic Organ Overdrive",
"Pulsing Prism Pulse",
"Quasar Quiet Quiver",
"Radiant Rain Resonance",
"Sonic Starlight Strum",
"Tranquil Twilight Twinkle",
"Universal Uplift Uproar",
"Vibrant Void Vroom",
"Dog bark",
"Rain on roof",
"Funky slap bass",
"Thunder rumble",
"Leaves rustling",
"Cat meowing",
"Piano keys playing",
"Violin strings vibrating",
"Drum beats pounding",
"Car horn honking",
"Waterfall crashing",
"Birds chirping",
"Wind howling",
"Glass shattering",
"Baby crying",
"Footsteps on gravel",
"Ocean waves breaking",
"Fire crackling",
"Telephone ringing",
"Doorbell chiming",
"Clock ticking",
"Keyboard typing",
"Sirens wailing",
"Applause clapping",
"Snoring softly",
"Heartbeat thumping",
"Bell ringing",
"Guitar strumming",
"Harp glissando",
"Trumpet blaring",
"Saxophone wailing",
"Clarinet squeaking",
"Flute trilling",
"Cymbals crashing",
"Bubbles popping",
"Whispering voices",
"Laughing heartily",
"Sneezing loudly",
"Coughing harshly",
"Hiccups echoing",
"Chewing crunchily",
"Soup slurping",
"Teeth brushing",
"Hair dryer blowing",
"Vacuum cleaner humming",
"Washing machine whirring",
"Raindrops pattering",
"Thunderstorm booming",
"Lightning cracking",
"Ice cracking",
"Snow crunching",
"Skate blades slicing",
"Basketball bouncing",
"Tennis ball hitting",
"Golf club swinging",
"Bowling pins crashing",
"Soccer ball kicking",
"Bicycle bell ringing",
"Skateboard rolling",
"Horse hooves clomping",
"Cow mooing",
"Sheep bleating",
"Pig snorting",
"Chicken clucking",
"Duck quacking",
"Eagle screeching",
"Owl hooting",
"Frog croaking",
"Bee buzzing",
"Mosquito whining",
"Fly buzzing",
"Spider web vibrating",
"Ants marching",
"Snake hissing",
"Lion roaring",
"Tiger growling",
"Elephant trumpeting",
"Monkey chattering",
"Gorilla grunting",
"Kangaroo hopping",
"Whale singing",
"Dolphin clicking",
"Seal barking",
"Penguin squawking",
"Gull crying",
"Albatross soaring",
"Hawk swooping",
"Parrot talking",
"Canary singing",
"Finch chirping",
"Woodpecker tapping",
"Crow cawing",
"Raven croaking",
"Dove cooing",
"Swallow twittering",
"Lark warbling",
"Nightingale singing",
"Robin chirping",
"Sparrow tweeting",
"Firework exploding",
"Gunshot firing",
"Cannon booming",
"Bomb detonating",
"Explosion erupting",
"Rocket launching",
"Missile whistling",
"Tank rumbling",
"Jet engine roaring",
"Helicopter whirring",
"Propeller spinning",
"Submarine sonar pinging",
"Ship horn blasting",
"Train whistle blowing",
"Car engine revving",
"Motorcycle vrooming",
"Truck horn honking",
"Bicycle gears shifting",
"Scooter engine puttering",
"Roller coaster screaming",
"Ferris wheel creaking",
"Amusement park music playing",
"Arcade game beeping",
"Slot machine ringing",
"Roulette wheel spinning",
"Cards shuffling",
"Dice rolling",
"Chess clock clicking",
"Poker chips clinking",
"Bowling ball rolling",
"Darts hitting board",
"Boxing bell dinging",
"Wrestlers grappling",
"Marathon runners panting",
"Swimmers splashing",
"Divers plunging",
"Skiers swooshing",
"Snowboarders carving",
"Ice skaters gliding",
"Hockey puck sliding",
"Baseball bat cracking",
"Football being kicked",
"Rugby scrum shouting",
"Cricket bat hitting",
"Ping pong ball pinging",
"Badminton shuttlecock whizzing",
"Volleyball being spiked",
"Gymnast landing",
"Weightlifters grunting",
"Judo fighters tumbling",
"Fencers clashing",
"Archer's bow releasing",
"Bullet train passing",
"Airplane taking off",
"Space shuttle blasting",
"Tractor plowing",
"Chainsaw cutting",
"Jackhammer pounding",
"Drill whirring",
"Saw slicing",
"Hammer hitting",
"Screwdriver twisting",
"Wrench turning",
"Pliers gripping",
"Shovel digging",
"Rake scraping",
"Hoe chopping",
"Axe chopping",
"Scissors cutting",
"Paper tearing",
"Pen writing",
"Pencil sketching",
"Marker drawing",
"Chalk squeaking",
"Eraser rubbing",
"Stapler clicking",
"Tape unrolling",
"Glue squeezing",
"Paintbrush stroking",
"Spray paint hissing",
"Airbrush spraying",
"Camera shutter clicking",
"Flashbulb popping",
"Film projector whirring",
"Video camera recording",
"Microphone feedback",
"Speaker blasting",
"Headphones humming",
"Record player scratching",
"CD spinning",
"Tape rewinding",
"Radio tuning",
"Turntable spinning",
"Amplifier buzzing",
"Electric guitar wailing",
"Bass guitar grooving",
"Acoustic guitar strumming",
"Banjo plucking",
"Mandolin ringing",
"Ukulele humming",
"Harpsichord playing",
"Organ pipes sounding",
"Synthesizer beeping",
"Drum machine ticking",
"Conga drums beating",
"Bongo drums tapping",
"Timpani booming",
"Xylophone tinkling",
"Vibraphone vibrating",
"Marimba resonating",
"Steel drums ringing",
"Gong crashing",
"Bell tower chiming",
"Church bells tolling",
"Carillon playing",
"Handbells ringing",
"Wind chimes tinkling",
"Theremin whistling",
"Melodica blowing",
"Accordion squeezing",
"Harmonica wailing",
"Pan flute whistling",
"Recorder playing",
"Oboe humming",
"English horn crooning",
"Bassoon buzzing",
"Contrabassoon growling",
"French horn blaring",
"Trombone sliding",
"Tuba booming",
"Euphonium belting",
"Cornet chirping",
"Bugle calling",
"Flugelhorn singing",
"Mellophone echoing",
"Baritone horn resounding",
"Sousaphone bellowing",
"Alphorn resonating",
"Didgeridoo droning",
"Bagpipes skirling",
"Uilleann pipes lilting",
"Shofar sounding",
"Vuvuzela buzzing",
"Kazoo humming",
"Whistle blowing",
"Siren alerting",
"Alarm clock beeping",
"Smoke detector chirping",
"Carbon monoxide detector warning",
"Security alarm wailing",
"Car alarm blaring",
"Fire alarm sounding",
"Emergency alert broadcasting",
"Pager beeping",
"Walkie-talkie crackling",
"Two-way radio transmitting",
"Satellite signal beeping",
"Morse code tapping",
"Telegraph clicking",
"Typewriter clacking",
"Cash register ringing",
"ATM dispensing",
"Vending machine dispensing",
"Elevator dinging",
"Escalator whirring",
"Conveyor belt moving",
"Factory machinery operating",
"Welding sizzling",
"Forge hammering",
"Loom weaving",
"Printing press running",
"Photocopier copying",
"Scanner scanning",
"Fax machine transmitting",
"Computer booting up",
"Laptop starting",
"Tablet swiping",
"Smartphone ringing",
"Cell phone vibrating",
"Pager beeping",
"Smartwatch alerting",
"VR headset immersing",
"AR glasses projecting",
"Drone buzzing",
"Robot moving",
"AI speaking",
"Virtual assistant responding",
"GPS navigating",
"Car navigation directing",
"Air traffic control guiding",
"Train conductor announcing",
"Bus driver calling",
"Subway train departing",
"Streetcar bell ringing",
"Cable car clanging",
"Ferry horn tooting",
"Sailboat rigging clinking",
"Motorboat engine revving",
"Yacht sailing",
"Rowboat oars splashing",
"Canoe paddling",
"Kayak gliding",
"Raft floating",
"Surfboard cutting",
"Windsurfing harnessing",
"Kitesurfing soaring",
"Paragliding whooshing",
"Hang gliding gliding",
"Hot air balloon inflating",
"Parachute opening",
"Skydiving adrenaline rushing",
"Bungee jumping screaming",
"Zip-lining zipping",
"Dog bark.",
"Rain on roof.",
"Funky slap bass.",
"Thunder rumble.",
"Waves crashing.",
"Leaves rustling.",
"Keyboard typing.",
"Bird chirping.",
"Train whistle.",
"Clock ticking.",
"Car horn.",
"Doorbell ringing.",
"Footsteps on gravel.",
"Cat meowing.",
"Fire crackling.",
"Wind howling.",
"Guitar strumming.",
"Baby laughing.",
"Applause.",
"Helicopter blades.",
"Church bells.",
"Sizzling bacon.",
"Typewriter clacking.",
"Owl hooting.",
"Bubble popping.",
"Water dripping.",
"Violin playing.",
"Cow mooing.",
"Camera shutter.",
"Horse galloping.",
"Bicycle bell.",
"Knocking on wood.",
"Telephone ringing.",
"Skateboard rolling.",
"Whistle blowing.",
"Motorcycle revving.",
"Airplane taking off.",
"Creaking door.",
"Saxophone solo.",
"Cricket chirping.",
"Chainsaw buzzing.",
"Drum roll.",
"Sneeze.",
"Electric guitar riff.",
"Frogs croaking.",
"Zipper zipping.",
"Hammer hitting nail.",
"Harp glissando.",
"Rooster crowing.",
"Stream flowing.",
"Ping pong ball.",
"Soda can opening.",
"Ambulance siren.",
"Trumpet fanfare.",
"Snoring.",
"Kids playing.",
"Raindrops on window.",
"Fingers snapping.",
"Cash register.",
"Jet engine.",
"Cymbal crash.",
"Kettle whistling.",
"Pigeons cooing.",
"Piano chord.",
"High heels on tile.",
"Lawnmower.",
"Crow cawing.",
"Orchestra tuning.",
"Seagulls calling.",
"Door slamming.",
"Fireworks.",
"Tap dancing.",
"Lion roaring.",
"Ball bouncing.",
"Flute melody.",
"Subway train.",
"Electric drill.",
"Bubble gum pop.",
"Waterfall.",
"Elevator ding.",
"Sheep bleating.",
"Thunderclap.",
"Glass breaking.",
"Balloon deflating.",
"Ice cubes clinking.",
"Wind chimes.",
"Snapping twig.",
"Scissors cutting.",
"Heartbeat.",
"Blender.",
"Chewing.",
"Bees buzzing.",
"Accordion playing.",
"Car alarm.",
"Roller coaster.",
"Bell ringing.",
"Sliding door.",
"Whistling kettle.",
"Slot machine.",
"Gas hissing.",
"Duck quacking.",
"Gunshot.",
"Golf ball hit.",
"Gavel bang.",
"Cello bowing.",
"Metal clang.",
"Heavy rain.",
"Coin dropping.",
"Drumsticks counting.",
"Cash register.",
"Camera focus beep.",
"Fire alarm.",
"Electric fan.",
"Laser beam.",
"Thunder and lightning.",
"Race car.",
"Steam whistle.",
"Door creak.",
"Mouse click.",
"Typing on phone.",
"Digital beep.",
"Footsteps in snow.",
"Children laughing.",
"Birds at dawn.",
"Rainforest ambiance.",
"Air horn.",
"Vacuum cleaner.",
"Helicopter hovering.",
"Ping pong game.",
"Running water.",
"Match strike.",
"Wind in trees.",
"Street music.",
"Morse code.",
"Drum solo.",
"Digital alarm.",
"Seashell sound.",
"Kettle boiling.",
"Firecracker.",
"Car engine.",
"Wine pouring.",
"Digital watch alarm.",
"Swishing skirt.",
"Rusty hinge.",
"Popcorn popping.",
"Rustling leaves.",
"Paper tearing.",
"Clothes dryer.",
"Banjo plucking.",
"Fire truck siren.",
"Air conditioner.",
"Plastic bag rustling.",
"Ice cracking.",
"Skateboard trick.",
"Bike chain.",
"Frog jumping.",
"Harpsichord.",
"Snapping rubber band.",
"Horse neighing.",
"Frying food.",
"Train crossing bell.",
"Slurping soup.",
"Pencil writing.",
"Soda fizzing.",
"Ocean waves.",
"Splashing water.",
"Clicking pen.",
"Pouring rain.",
"Boat horn.",
"Windshield wipers.",
"Horse trotting.",
"Clapping hands.",
"Car starting.",
"Dog bark",
"Rain on roof",
"Funky slap bass",
"Thunder rumble",
"Cat meowing",
"Waves crashing",
"Wind howling",
"Birds chirping",
"Leaves rustling",
"Footsteps on gravel",
"Typing on keyboard",
"Car horn honking",
"Clock ticking",
"Doorbell ringing",
"Fire crackling",
"Baby crying",
"Train whistle",
"Piano playing",
"Applause",
"Glass shattering",
"Motorcycle revving",
"Sizzling frying pan",
"Telephone ringing",
"Violin string",
"Drum beats",
"Whistling",
"Coughing",
"Horse trotting",
"Stream flowing",
"Owl hooting",
"Electric guitar riff",
"Camera shutter clicking",
"Saxophone melody",
"Helicopter blades",
"Sneezing",
"Laughing",
"Bee buzzing",
"Chainsaw cutting",
"Airplane taking off",
"Bubbles popping",
"Harmonica solo",
"Water dripping",
"Scissors cutting",
"Skateboard rolling",
"Hail hitting window",
"Creaky floorboard",
"Ball bouncing",
"Bell tolling",
"Thunderstorm",
"Heartbeat",
"Door creaking",
"Snoring",
"Flute trill",
"Harp glissando",
"Crow cawing",
"Fire alarm",
"Trumpet fanfare",
"Cash register",
"Waterfall",
"Rooster crowing",
"Fingers snapping",
"Skateboarding",
"Electric drill",
"Blender whirring",
"Tambourine shake",
"Knocking on door",
"Balloon popping",
"Can opening",
"Fireworks",
"Vacuum cleaner",
"Frog croaking",
"Cricket chirping",
"Sirens",
"Guitar strumming",
"Cow mooing",
"Wind chimes",
"Keyboard clacking",
"Children playing",
"Gas stove igniting",
"Whistle blowing",
"Gong",
"Typewriter",
"Raindrop",
"Kettle whistling",
"Wood chopping",
"Subway train",
"Vuvuzela",
"Thunder clap",
"Popcorn popping",
"Church bells",
"Engine starting",
"Ice cracking",
"Sawing wood",
"River flowing",
"Soda fizzing",
"Laser beam",
"Clicking pen",
"Train passing",
"Cymbal crash",
"Jackhammer",
"Zipper closing",
"Paper tearing",
"Maracas shaking",
"Jet engine",
"Metal clanging",
"Door slamming",
"Bubble wrap popping",
"Slot machine",
"Brushing hair",
"Chewing",
"Wolf howling",
"Accordion playing",
"Car alarm",
"Washing machine",
"Eagle screech",
"Rainforest ambience",
"Boxing bell",
"Typing on a smartphone",
"Digital alarm",
"Bicycle bell",
"Parrot talking",
"Drum roll",
"High heels clacking",
"Ball hitting racket",
"Camera flash",
"Electric shaver",
"Violin pizzicato",
"Mouse clicking",
"Door locking",
"Electric fan",
"Cork popping",
"Coin dropping",
"Horse galloping",
"Kettle drum",
"Electric toothbrush",
"Spray bottle",
"Car skidding",
"Whipping air",
"Boiling water",
"Hammering nail",
"Clarinet solo",
"Shuffling cards",
"Ping pong",
"Gargling water",
"Woodpecker pecking",
"Dice rolling",
"Trash bag rustling",
"Guitar tuning",
"Tuba playing",
"Stapler",
"Rolling dice",
"Ticking stopwatch",
"Fire extinguisher",
"Rusty hinge",
"Car wash",
"Skateboard ollie",
"Frog jumping",
"Clock chime",
"Zipping tent",
"Chopping vegetables",
"Air horn",
"Metal detector",
"Windshield wipers",
"Frying bacon",
"Guitar slide",
"Rock tumbling",
"Corkscrew",
"Electric razor",
"Arrow hitting target",
"Broom sweeping",
"Computer startup",
"Can crusher",
"Paper shredder",
"Dog whistle",
"Skateboard grinding",
"Seagull calling",
"Gears turning",
"Water boiling",
"Pool ball break",
"Typing on a tablet",
"Ice cube tray",
"Steel drum",
"Record scratch",
"Breaking stick",
"Typing on a laptop",
"Piano tuning",
"Seashell echo",
"Drumsticks",
"Electric mixer",
"Coin toss",
"Ripping fabric",
"Kicking a ball",
"Cell phone vibration",
"Leaf blower",
"Car gear shift",
"Drawer opening",
"Drum pedal",
"Elevator ding",
"Gas burner",
"Ratchet wrench",
]